T14637 fix install directory
andersson/bootrr pull request #23
Opened 2019-05-09 12:18 UTC by gctucker

This is to always keep the `boards` and `helpers` directories when installing `bootrr`, to make `bootrr-auto` work in the same way regardless of where it's installed.

2019-05-10 10:17 UTC, aragua approved these changes
LGTM

2019-05-23 22:18 UTC, andersson requested changes

2019-05-23 22:18 UTC, andersson commented on Makefile
> +all-install += $(DESTDIR)$(prefix)/$1/$2
Doesn't the board scripts still rely on the helpers being in $PATH? How do you ensure that this is the case?

2019-05-24 09:22 UTC, gctucker commented on Makefile
> +all-install += $(DESTDIR)$(prefix)/$1/$2
Yes, the LAVA jobs are doing this now:
```
            - export PATH=/opt/bootrr/helpers:$PATH
            - cd /opt/bootrr && sh helpers/bootrr-auto
```
I guess `bootrr-auto` could also do that directly with `export PATH=$(pwd)/helpers:$PATH`.  In the end, it depends what we want to do.  At least with the approach in this patch, we're not installing all the helpers and the board files together in the system path so it'a bit cleaner imho.  The only convention is that the current directory needs to be the installation path i.e. `/opt/bootrr/` in the example above.

2019-06-03 19:30 UTC, alimon reviewed
@gctucker What is bootrr-generic-tests target?, I didn't see into main Makefile.

2019-06-03 20:35 UTC, gctucker commented
@alimon I'm not entirely sure I understand your question.  There's a patch in this PR to install `bootrr-generic-tests` as it was previously added to the repository but not to the list of files to install in the Makefile.  It's for things that can be run on any platform, like checking there aren't any kernel devices that were not probed.

2019-06-04 19:16 UTC, alimon commented
@gctucker Ok, LGTM.

2019-06-07 06:42 UTC, gctucker commented
After discussing this with @andersson on IRC, we've agreed that having a `bootrr` launcher command in the system path and the boards and helpers installed in a separate directory was the best way to address this issue.  I'll start working on this next week.

2022-06-09 19:39 UTC, closed without merging